language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "Nl6gim0fCFM6LfGVkBQg1XJwMfgGiotzbxUZpo1YgDcGCbTVxlGU/RwVevFrl8S4Bq7wF4CCkJZd0ih3ebIDS4lSRQnXFVX/OGbj4ZW9RxiBHiRN0qGs6I6iotsELpVlUrjowTiYLBksFbeDSkxNQDfA0mAGqEG6m9MvaA3NWFHITUGOBbMG0uJXQAKsCqedM3SbWgh1fIKUapdeYXZ1xnN/d3R2D2AIbzsvz/7ooElj0xSBZanatIDUjyQHvAbe1KnUU9ddbDyb2M86t9PSXasMY6tvcKdy7CObGQ3cj6+IHUPyuoFZ4gyMZYTYbKEu3jK69L4eV2/P6zpN+Q455ShKu7PRDRiA8djdxhy8oOvYhld0RRHeklRupAgUGTzeV8F0h7ZAToVe+z+aXqxoh2DIoZ3WmdFJZQqX2f9ABjC0isTYwFbytdaKb6+RMP9UfITrZmc0stXvGQcfNOB9OYTQMGeb/pjymaYbL7FrHBp8lahJTz3NpCMxBxKVlYI2S1HL/pINjgAzqNLreVJJ2XSK1uHKk6gax/ZM3/PwDERdRBMWx4vOs9P8jlT3GDuxPfb02V23Tv+NrklWnnvPlKXNO+tNgJBC8vAoeo0+YJlfTW0YSHVa3qlkk8CxLhqsVgq9H+4FX91MD1HmApCpHD7rq5UujHgQwJUlu6PTdgw="
  secret_access_key:
    secure: "YnhJ0yw4q4AfTmjbPmZy0+FYaJF5JB34Czz4VdaVlixdFuR11bByYsMMvaLXmLj68TmZBygip8FmhwYYbz6XW1RW94YCtlodxmpPMX/N5KYCSN9iAzjmronsxcjPjWgxN2r0O7vfeBbnRFjC82xOg3fxN02BJXw4wsVL0R2YwceHv6Hxd33by+D2d8c3vsIZSqkhe2FByLPRzxxp2lHEu4onXGkSk7RI74gbY9xYZyok+KLrkckPU4Ga5+ECt10RQZTKVN9nC9zkpdHHIw+nbMqlx+MVeaYMGQcJ36uvVeJN1MaT5EhGTeqWv8ea0DtIjQhZyc176BC1OUUt898F5TD1W49Dk01O77JuwRHtZamYSrHgwJkrgQQylUaa03iSKy1/3Ayla/+06GLEblbl0QvDHJ23OmvR3MJmvLHSKgC7OG0pQLHIqphmU7s2BcEf4abTqDwk780tusvdrMPaqL+C+PNyzrOAtHU4uQInYV/iY/r2/+WOpFCPQEUESTDYwVC21ipnpR/A0FNiFn7t6DnqeM65lJCxhznWwySXIZg6E1pVZbbQthexOnmR8QMPZv63q/X5RYoBUW/rJPuSaS/Nh6hPSbNZv9LsSzQksPrZ9QswjlFYjDV9dqfhQ/UYFm5XKbWiYHdlyRM+vfjGt28dNuA2hhGDK1jU8asI30E="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/puncast
